using System.Reflection;
using System.Text.Json.Serialization;

namespace ThemModdingHerds.Models.GLTF;
public class Asset : Property
{
    [JsonPropertyName("copyright")]
    public string? Copyright {get;set;}
    public const string GENERATOR = "ThemModdingHerds.Models";
    [JsonPropertyName("generator")]
    public string? Generator {get;set;} = GENERATOR;
    public const string VERSION = "2.0";
    [JsonPropertyName("version")]
    public string Version {get;set;} = VERSION;
    [JsonPropertyName("minVersion")]
    public string? MinVersion {get;set;}
    public override string ToString()
    {
        return $"v{Version} generated by {Generator ?? "something"}";
    }
}